# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MDIT_About.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(500, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(500, 330))
        Dialog.setMaximumSize(QtCore.QSize(500, 330))
        self.label_logo = QtWidgets.QLabel(Dialog)
        self.label_logo.setGeometry(QtCore.QRect(0, 0, 501, 101))
        self.label_logo.setObjectName("label_logo")
        self.label_about = QtWidgets.QLabel(Dialog)
        self.label_about.setGeometry(QtCore.QRect(10, 110, 481, 211))
        self.label_about.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_about.setObjectName("label_about")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "關於..."))
        self.label_logo.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/Photos/Photos/MDI_logo.jpg\"/></p></body></html>"))
        self.label_about.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">MDIT打卡系統 (MDIT Punch Card System)</span></p><p><span style=\" font-size:16pt;\">Ver. 0.2.2</span></p><p><br/></p><p><span style=\" font-size:16pt;\">Design by Keaton Yang</span></p><p><span style=\" font-size:16pt;\">Update: 2022/10/14</span></p></body></html>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
