# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MDIT_Staff.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 614)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tblStaff = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblStaff.sizePolicy().hasHeightForWidth())
        self.tblStaff.setSizePolicy(sizePolicy)
        self.tblStaff.setObjectName("tblStaff")
        self.tblStaff.setColumnCount(5)
        self.tblStaff.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblStaff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblStaff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblStaff.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblStaff.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tblStaff.setHorizontalHeaderItem(4, item)
        self.horizontalLayout.addWidget(self.tblStaff)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setMinimumSize(QtCore.QSize(150, 50))
        self.btnDelete.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnDelete.setObjectName("btnDelete")
        self.verticalLayout_2.addWidget(self.btnDelete)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.btnInsert = QtWidgets.QPushButton(self.centralwidget)
        self.btnInsert.setMinimumSize(QtCore.QSize(150, 50))
        self.btnInsert.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btnInsert.setObjectName("btnInsert")
        self.verticalLayout_2.addWidget(self.btnInsert)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lblStatus = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStatus.sizePolicy().hasHeightForWidth())
        self.lblStatus.setSizePolicy(sizePolicy)
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MDIT成員編輯"))
        item = self.tblStaff.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tblStaff.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名稱"))
        item = self.tblStaff.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "資料"))
        item = self.tblStaff.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "打卡聲"))
        item = self.tblStaff.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "e-mail"))
        self.btnDelete.setText(_translate("MainWindow", "刪除數列"))
        self.btnInsert.setText(_translate("MainWindow", "插入一列"))
        self.lblStatus.setText(_translate("MainWindow", "請在左方表格內雙擊滑鼠左鍵進行編輯，完成後請按Enter編輯"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
